import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxWrapper from "@/provider/redux/ReduxWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxWrapper>
      <html lang="en">
        <body className={inter.className}>
          <div className="max-w-3xl mx-auto">
            <h1>Navbar</h1>
            {children}
          </div>
        </body>
      </html>
    </ReduxWrapper>
  );
}
